apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-deep-dive-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL:  https://github.com/roeebronfeld/deep-dive-devops-platform-app.git
    targetRevision: main
    path: helm/deep-dive-devops-platform
    helm:
      values: |
        backend:
          replicaCount: 4
        frontend:
          replicaCount: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: default
